default:
    host:                   localhost
    
testing:
    adapter:
    database:
    username:
    password:
    database_file:
    port:
    options:
    
    
development:
    adapter:                mysql
    database:
    username:
    password:
    database_file:
    port:
    options:
    
production:
    adapter:                mysql
    database:
    username:
    password:
    database_file:
    port:
    options: